services:
  btb-service:
    image: btb-service:latest
    container_name: btb-service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 0
    # env_file: 
    #   - .env
    ports:
      - "30001:30001"
    restart: always
    volumes:
      - ~/../apps/assets:/app/btb-service/assets
      - ~/../apps/uploads:/app/btb-service/uploads
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
    networks:
       - aryanattapt-network
        
networks:
  aryanattapt-network:
    name: aryanattapt-network
    external: true