services:
  btbschool-service:
    image: btbschool-service:latest
    container_name: btbschool-service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 0
    env_file: 
      - .env.production
    ports:
      - "30001:30001"
    restart: always
    volumes:
      - ~/../apps/assets:/app/btbschool-service/assets
      - ~/../apps/uploads:/app/btbschool-service/uploads
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
    networks:
       - aryanattapt-network
        
networks:
  aryanattapt-network:
    name: aryanattapt-network
    external: true